device_info:
  device:
    name: soft_gripper
  manufacturer:
    name: Soft Robotics
    uuid: 11111111-1111-1111-1111-111111111111
  model:
    name: mGrip_P2
    uuid: 22222222-2222-2222-2222-222222222222
  user_description: mGrip P2 Soft Gripper
  serial_number: 123456789
  device_classes:
    - class_identifier:
        name: gripper
        uuid: 33333333-3333-3333-3333-333333333333
      subclasses: 
        - soft
  implemented_types:
    - com.robotraconteur.robotics.tool.Tool
tool_type: soft_gripper
tool_capabilities:
- open_close_command
tcp:
  translation:
    x: 0
    y: 0
    z: 0.1577
  rotation:
    x: 0
    y: 0
    z: 0
    w: 1
close_position: 0
open_position: 1
command_min: 0
command_max: 1
command_close: 0
command_open: 1
sensor_min:
sensor_max:
